using System;
using System.Linq;
using System.Text;
using GenericDto.Analyzers.Extensions;
using GenericDto.Analyzers.Generators.Incremental;
using Microsoft.CodeAnalysis;

namespace GenericDto.Analyzers.Generators;

/// <summary>
/// Builder class responsible for generating mapper extension methods between source types and DTOs.
/// </summary>
internal static class MapperCodeBuilder
{
    public static string GenerateMapper(DtoGenerationContext context)
    {
        var sb = new IndentedStringBuilder();

        // File header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// This code was generated by GenericDto Source Generator.");
        sb.AppendLine("// Do not modify this file manually.");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Usings
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");

        var sourceNamespace = context.SourceType.ContainingNamespace.ToDisplayString();
        if (!string.IsNullOrEmpty(sourceNamespace))
        {
            sb.AppendLine($"using {sourceNamespace};");
        }
        if (context.TargetNamespace != sourceNamespace)
        {
            sb.AppendLine($"using {context.TargetNamespace};");
        }
        sb.AppendLine();

        // Namespace
        sb.AppendLine($"namespace {context.TargetNamespace}");
        sb.AppendLine("{");
        sb.IncreaseIndent();

        // Static mapper class
        WriteMapperClass(sb, context);

        sb.DecreaseIndent();
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void WriteMapperClass(IndentedStringBuilder sb, DtoGenerationContext context)
    {
        var sourceTypeName = context.SourceType.Name;
        var sourceTypeFullName = context.SourceType.ToDisplayString();
        var dtoName = context.DtoClassName;
        
        // Get the access modifier from the DTO attribute
        var accessModifier = context.GenerateDtoAttribute.GetNamedArgument<string>("AccessModifier") ?? "public";

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Extension methods for mapping between <see cref=\"{sourceTypeFullName}\"/> and <see cref=\"{dtoName}\"/>.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"GenericDto.Analyzers\", \"1.0.0\")]");
        sb.AppendLine("[global::System.Diagnostics.DebuggerNonUserCodeAttribute]");
        sb.AppendLine("[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]");
        sb.AppendLine($"{accessModifier} static class {dtoName}MapperExtensions");
        sb.AppendLine("{");
        sb.IncreaseIndent();

        // ToDto extension method
        WriteToDto(sb, context, sourceTypeName, sourceTypeFullName, dtoName);
        sb.AppendLine();

        // ToEntity extension method (reverse mapping)
        WriteToEntity(sb, context, sourceTypeName, sourceTypeFullName, dtoName);
        sb.AppendLine();

        // Collection mapping methods
        WriteToDtoCollection(sb, context, sourceTypeName, sourceTypeFullName, dtoName);
        sb.AppendLine();

        WriteToEntityCollection(sb, context, sourceTypeName, sourceTypeFullName, dtoName);
        sb.AppendLine();

        // Update entity from DTO
        WriteUpdateEntity(sb, context, sourceTypeName, sourceTypeFullName, dtoName);

        sb.DecreaseIndent();
        sb.AppendLine("}");
    }

    private static void WriteToDto(IndentedStringBuilder sb, DtoGenerationContext context, string sourceTypeName, string sourceTypeFullName, string dtoName)
    {
        var isSourceValueType = context.SourceType.IsValueType;
        
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Maps a <see cref=\"{sourceTypeFullName}\"/> instance to a new <see cref=\"{dtoName}\"/> instance.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"/// <param name=\"source\">The source {sourceTypeName} instance.</param>");
        sb.AppendLine($"/// <returns>A new {dtoName} instance with mapped values.</returns>");
        sb.AppendLine($"public static {dtoName} ToDto(this {sourceTypeFullName} source)");
        sb.AppendLine("{");
        sb.IncreaseIndent();
        
        // Only add null check for reference types
        if (!isSourceValueType)
        {
            sb.AppendLine("if (source is null)");
            sb.AppendLine("{");
            sb.IncreaseIndent();
            sb.AppendLine("throw new global::System.ArgumentNullException(nameof(source));");
            sb.DecreaseIndent();
            sb.AppendLine("}");
            sb.AppendLine();
        }
        
        sb.AppendLine($"return new {dtoName}");
        sb.AppendLine("{");
        sb.IncreaseIndent();

        foreach (var property in context.Properties)
        {
            var sourcePropertyName = property.SourceProperty.Name;
            sb.AppendLine($"{property.PropertyName} = source.{sourcePropertyName},");
        }

        sb.DecreaseIndent();
        sb.AppendLine("};");
        sb.DecreaseIndent();
        sb.AppendLine("}");
    }

    private static void WriteToEntity(IndentedStringBuilder sb, DtoGenerationContext context, string sourceTypeName, string sourceTypeFullName, string dtoName)
    {
        // Check if source type has a parameterless constructor
        var hasParameterlessConstructor = context.SourceType.InstanceConstructors
            .Any(c => c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public);

        if (!hasParameterlessConstructor)
        {
            sb.AppendLine("// Note: ToEntity method not generated because source type lacks a public parameterless constructor.");
            return;
        }

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Maps a <see cref=\"{dtoName}\"/> instance to a new <see cref=\"{sourceTypeFullName}\"/> instance.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"/// <param name=\"dto\">The source {dtoName} instance.</param>");
        sb.AppendLine($"/// <returns>A new {sourceTypeName} instance with mapped values.</returns>");
        sb.AppendLine($"public static {sourceTypeFullName} ToEntity(this {dtoName} dto)");
        sb.AppendLine("{");
        sb.IncreaseIndent();
        sb.AppendLine("if (dto is null)");
        sb.AppendLine("{");
        sb.IncreaseIndent();
        sb.AppendLine("throw new global::System.ArgumentNullException(nameof(dto));");
        sb.DecreaseIndent();
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"return new {sourceTypeFullName}");
        sb.AppendLine("{");
        sb.IncreaseIndent();

        // Only map properties that have a setter on the source type
        foreach (var property in context.Properties)
        {
            var sourceProperty = property.SourceProperty;
            if (sourceProperty.SetMethod != null && sourceProperty.SetMethod.DeclaredAccessibility == Accessibility.Public)
            {
                sb.AppendLine($"{sourceProperty.Name} = dto.{property.PropertyName},");
            }
        }

        sb.DecreaseIndent();
        sb.AppendLine("};");
        sb.DecreaseIndent();
        sb.AppendLine("}");
    }

    private static void WriteToDtoCollection(IndentedStringBuilder sb, DtoGenerationContext context, string sourceTypeName, string sourceTypeFullName, string dtoName)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Maps a collection of <see cref=\"{sourceTypeFullName}\"/> instances to a list of <see cref=\"{dtoName}\"/> instances.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"/// <param name=\"source\">The source collection.</param>");
        sb.AppendLine($"/// <returns>A list of {dtoName} instances with mapped values.</returns>");
        sb.AppendLine($"public static global::System.Collections.Generic.List<{dtoName}> ToDtoList(this global::System.Collections.Generic.IEnumerable<{sourceTypeFullName}> source)");
        sb.AppendLine("{");
        sb.IncreaseIndent();
        sb.AppendLine("if (source is null)");
        sb.AppendLine("{");
        sb.IncreaseIndent();
        sb.AppendLine("throw new global::System.ArgumentNullException(nameof(source));");
        sb.DecreaseIndent();
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("return source.Select(x => x.ToDto()).ToList();");
        sb.DecreaseIndent();
        sb.AppendLine("}");
    }

    private static void WriteToEntityCollection(IndentedStringBuilder sb, DtoGenerationContext context, string sourceTypeName, string sourceTypeFullName, string dtoName)
    {
        // Check if source type has a parameterless constructor
        var hasParameterlessConstructor = context.SourceType.InstanceConstructors
            .Any(c => c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public);

        if (!hasParameterlessConstructor)
        {
            sb.AppendLine("// Note: ToEntityList method not generated because source type lacks a public parameterless constructor.");
            return;
        }

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Maps a collection of <see cref=\"{dtoName}\"/> instances to a list of <see cref=\"{sourceTypeFullName}\"/> instances.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"/// <param name=\"dtos\">The source DTO collection.</param>");
        sb.AppendLine($"/// <returns>A list of {sourceTypeName} instances with mapped values.</returns>");
        sb.AppendLine($"public static global::System.Collections.Generic.List<{sourceTypeFullName}> ToEntityList(this global::System.Collections.Generic.IEnumerable<{dtoName}> dtos)");
        sb.AppendLine("{");
        sb.IncreaseIndent();
        sb.AppendLine("if (dtos is null)");
        sb.AppendLine("{");
        sb.IncreaseIndent();
        sb.AppendLine("throw new global::System.ArgumentNullException(nameof(dtos));");
        sb.DecreaseIndent();
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("return dtos.Select(x => x.ToEntity()).ToList();");
        sb.DecreaseIndent();
        sb.AppendLine("}");
    }

    private static void WriteUpdateEntity(IndentedStringBuilder sb, DtoGenerationContext context, string sourceTypeName, string sourceTypeFullName, string dtoName)
    {
        var isSourceValueType = context.SourceType.IsValueType;
        
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Updates an existing <see cref=\"{sourceTypeFullName}\"/> instance with values from a <see cref=\"{dtoName}\"/>.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"/// <param name=\"entity\">The entity to update.</param>");
        sb.AppendLine($"/// <param name=\"dto\">The DTO containing the new values.</param>");
        sb.AppendLine($"/// <returns>The updated entity instance.</returns>");
        sb.AppendLine($"public static {sourceTypeFullName} UpdateFrom(this {sourceTypeFullName} entity, {dtoName} dto)");
        sb.AppendLine("{");
        sb.IncreaseIndent();
        
        // Only add null check for reference types
        if (!isSourceValueType)
        {
            sb.AppendLine("if (entity is null)");
            sb.AppendLine("{");
            sb.IncreaseIndent();
            sb.AppendLine("throw new global::System.ArgumentNullException(nameof(entity));");
            sb.DecreaseIndent();
            sb.AppendLine("}");
            sb.AppendLine();
        }
        
        sb.AppendLine("if (dto is null)");
        sb.AppendLine("{");
        sb.IncreaseIndent();
        sb.AppendLine("throw new global::System.ArgumentNullException(nameof(dto));");
        sb.DecreaseIndent();
        sb.AppendLine("}");
        sb.AppendLine();

        // Only update properties that have a setter on the source type
        foreach (var property in context.Properties)
        {
            var sourceProperty = property.SourceProperty;
            if (sourceProperty.SetMethod != null && sourceProperty.SetMethod.DeclaredAccessibility == Accessibility.Public)
            {
                sb.AppendLine($"entity.{sourceProperty.Name} = dto.{property.PropertyName};");
            }
        }

        sb.AppendLine();
        sb.AppendLine("return entity;");
        sb.DecreaseIndent();
        sb.AppendLine("}");
    }
}
