using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using GenericDto.Analyzers.Constants;
using GenericDto.Analyzers.Extensions;
using GenericDto.Analyzers.Generators.Incremental;
using Microsoft.CodeAnalysis;

namespace GenericDto.Analyzers.Generators;

/// <summary>
/// Builder class responsible for generating DTO source code.
/// </summary>
internal static class DtoCodeBuilder
{
    public static string GenerateDto(DtoGenerationContext context)
    {
        var indent = new IndentedStringBuilder();

        // File header
        indent.AppendLine("// <auto-generated/>");
        indent.AppendLine("// This code was generated by GenericDto Source Generator.");
        indent.AppendLine("// Do not modify this file manually.");
        indent.AppendLine();
        indent.AppendLine("#nullable enable");
        indent.AppendLine();

        // Usings
        WriteUsings(indent, context);
        indent.AppendLine();

        // Namespace
        indent.AppendLine($"namespace {context.TargetNamespace}");
        indent.AppendLine("{");
        indent.IncreaseIndent();

        // Class/Record declaration
        WriteTypeDeclaration(indent, context);
        indent.AppendLine("{");
        indent.IncreaseIndent();

        // Properties
        WriteProperties(indent, context);
        indent.AppendLine();

        // Constructors
        if (!context.UseRecord)
        {
            WriteConstructors(indent, context);
        }

        // IEquatable implementation
        if (context.ImplementIEquatable && !context.UseRecord)
        {
            WriteIEquatableImplementation(indent, context);
        }

        // IValidatableObject implementation
        if (context.ImplementIValidatableObject)
        {
            WriteIValidatableObjectImplementation(indent, context);
        }

        // ToString override
        if (!context.UseRecord && context.GenerateToString)
        {
            WriteToStringOverride(indent, context);
        }

        indent.DecreaseIndent();
        indent.AppendLine("}");

        indent.DecreaseIndent();
        indent.AppendLine("}");

        return indent.ToString();
    }

    private static void WriteUsings(IndentedStringBuilder sb, DtoGenerationContext context)
    {
        var usings = new HashSet<string>(GeneratorConstants.DefaultUsings);

        // Add source type namespace
        var sourceNamespace = context.SourceType.ContainingNamespace.ToDisplayString();
        if (!string.IsNullOrEmpty(sourceNamespace))
        {
            usings.Add(sourceNamespace);
        }

        // Add additional usings from attribute - use the safe extension method
        var additionalUsings = context.GenerateDtoAttribute.GetNamedArgumentAsStringArray("AdditionalUsings");
        foreach (var usingStr in additionalUsings)
        {
            usings.Add(usingStr);
        }

        if (context.ImplementIEquatable)
        {
            usings.Add("System");
        }

        if (context.ImplementIValidatableObject)
        {
            usings.Add("System.ComponentModel.DataAnnotations");
        }

        // Write sorted usings
        foreach (var usingStatement in usings.OrderBy(u => u))
        {
            sb.AppendLine($"using {usingStatement};");
        }
    }

    private static void WriteTypeDeclaration(
        IndentedStringBuilder sb,
        DtoGenerationContext context)
    {
        var interfaces = new List<string>();

        if (context.ImplementIEquatable && !context.UseRecord)
        {
            interfaces.Add($"global::System.IEquatable<{context.DtoClassName}>");
        }

        if (context.ImplementIValidatableObject)
        {
            interfaces.Add("global::System.ComponentModel.DataAnnotations.IValidatableObject");
        }

        var inheritance = interfaces.Count > 0 ? $" : {string.Join(", ", interfaces)}" : "";

        if (context.GenerateDocumentation)
        {
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// DTO class generated from <see cref=\"{context.SourceType.ToDisplayString()}\"/>.");
            sb.AppendLine("/// </summary>");
        }
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"GenericDto.Analyzers\", \"1.0.0\")]");
        sb.AppendLine("[global::System.Diagnostics.DebuggerNonUserCodeAttribute]");
        sb.AppendLine("[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]");

        var typeKeyword = context.UseRecord ? "record" : "partial class";
        sb.AppendLine($"{context.AccessModifier} {typeKeyword} {context.DtoClassName}{inheritance}");
    }

    private static void WriteProperties(IndentedStringBuilder sb, DtoGenerationContext context)
    {
        foreach (var property in context.Properties)
        {
            var effectiveType = property.EffectiveType;
            var isStringType = effectiveType.IsStringType();
            var isNumericType = effectiveType.IsNumericType();

            if (context.GenerateDocumentation)
            {
                sb.AppendLine("/// <summary>");
                if (!string.IsNullOrWhiteSpace(property.Description))
                {
                    sb.AppendLine($"/// {EscapeXml(property.Description!)}");
                }
                else
                {
                    sb.AppendLine($"/// Gets or sets the {property.PropertyName} value.");
                }
                sb.AppendLine("/// </summary>");
            }

            if (context.GenerateJsonAttributes)
            {
                WriteJsonAttributes(sb, property);
            }

            // Add required attribute if property is non-nullable reference type
            if (property.IsRequired)
            {
                sb.AppendLine("[global::System.ComponentModel.DataAnnotations.Required]");
            }

            // Add MaxLength validation attribute if specified
            if (property.MaxLength > 0 && isStringType)
            {
                sb.AppendLine($"[global::System.ComponentModel.DataAnnotations.MaxLength({property.MaxLength})]");
            }

            // Add MinLength validation attribute if specified
            if (property.MinLength > 0 && isStringType)
            {
                sb.AppendLine($"[global::System.ComponentModel.DataAnnotations.MinLength({property.MinLength})]");
            }

            // Add RegularExpression validation attribute if pattern is specified
            if (!string.IsNullOrWhiteSpace(property.Pattern) && isStringType)
            {
                // Escape quotes for verbatim string literal (backslashes don't need escaping with @"...")
                var escapedPattern = property.Pattern!.Replace("\"", "\"\"");
                sb.AppendLine($"[global::System.ComponentModel.DataAnnotations.RegularExpression(@\"{escapedPattern}\")]");
            }

            // Add Range validation attribute if both min and max values are explicitly set (not at extremes)
            if (property.MinValue != double.MinValue && property.MaxValue != double.MaxValue && isNumericType)
            {
                sb.AppendLine($"[global::System.ComponentModel.DataAnnotations.Range({property.MinValue}, {property.MaxValue})]");
            }

            WriteDtoValidationAttributes(sb, property);

            // Build property declaration
            var typeStr = property.PropertyType;
            if (property.IsNullable && !typeStr.EndsWith("?"))
            {
                typeStr += "?";
            }

            var requiredModifier = context.UseRequiredMembers && property.IsRequired ? "required " : string.Empty;
            var setter = context.UseInitOnlyProperties ? "init" : "set";
            var propertyDeclaration = $"public {requiredModifier}{typeStr} {property.PropertyName} {{ get; {setter}; }}";

            if (property.HasDefaultValue && property.DefaultValue != null)
            {
                propertyDeclaration += $" = {property.DefaultValue};";
            }
            else if (property.IsNullable)
            {
                propertyDeclaration += " = default!;";
            }
            else if (isStringType && !(context.UseRequiredMembers && property.IsRequired))
            {
                propertyDeclaration += " = string.Empty;";
            }

            sb.AppendLine(propertyDeclaration);
            sb.AppendLine();
        }
    }

    private static void WriteConstructors(IndentedStringBuilder sb, DtoGenerationContext context)
    {
        if (context.GenerateParameterlessConstructor)
        {
            if (context.GenerateDocumentation)
            {
                sb.AppendLine("/// <summary>");
                sb.AppendLine($"/// Initializes a new instance of the <see cref=\"{context.DtoClassName}\"/> class.");
                sb.AppendLine("/// </summary>");
            }
            sb.AppendLine($"public {context.DtoClassName}()");
            sb.AppendLine("{");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // Generate constructor with all properties
        if (context.Properties.Length > 0)
        {
            if (context.GenerateDocumentation)
            {
                sb.AppendLine("/// <summary>");
                sb.AppendLine($"/// Initializes a new instance of the <see cref=\"{context.DtoClassName}\"/> class with specified values.");
                sb.AppendLine("/// </summary>");
            }

            var parameters = context.Properties
                .Select(p =>
                {
                    var type = p.IsNullable && !p.PropertyType.EndsWith("?") ? $"{p.PropertyType}?" : p.PropertyType;
                    var paramName = p.PropertyName.ToCamelCase();
                    return $"{type} {paramName}";
                });

            sb.AppendLine($"public {context.DtoClassName}({string.Join(", ", parameters)})");
            sb.AppendLine("{");
            sb.IncreaseIndent();

            foreach (var property in context.Properties)
            {
                var paramName = property.PropertyName.ToCamelCase();
                sb.AppendLine($"this.{property.PropertyName} = {paramName};");
            }

            sb.DecreaseIndent();
            sb.AppendLine("}");
            sb.AppendLine();
        }
    }

    private static void WriteIEquatableImplementation(IndentedStringBuilder sb, DtoGenerationContext context)
    {
        sb.AppendLine("/// <inheritdoc/>");
        sb.AppendLine($"public bool Equals({context.DtoClassName}? other)");
        sb.AppendLine("{");
        sb.IncreaseIndent();
        sb.AppendLine("if (other is null) return false;");
        sb.AppendLine("if (ReferenceEquals(this, other)) return true;");

        if (context.Properties.Length > 0)
        {
            var comparisons = context.Properties
                .Select(p => $"global::System.Collections.Generic.EqualityComparer<{p.PropertyType}>.Default.Equals({p.PropertyName}, other.{p.PropertyName})");

            sb.AppendLine($"return {string.Join(" && ", comparisons)};");
        }
        else
        {
            sb.AppendLine("return true;");
        }

        sb.DecreaseIndent();
        sb.AppendLine("}");
        sb.AppendLine();

        // Override Equals(object)
        sb.AppendLine("/// <inheritdoc/>");
        sb.AppendLine("public override bool Equals(object? obj)");
        sb.AppendLine("{");
        sb.IncreaseIndent();
        sb.AppendLine($"return obj is {context.DtoClassName} other && Equals(other);");
        sb.DecreaseIndent();
        sb.AppendLine("}");
        sb.AppendLine();

        // Override GetHashCode
        sb.AppendLine("/// <inheritdoc/>");
        sb.AppendLine("public override int GetHashCode()");
        sb.AppendLine("{");
        sb.IncreaseIndent();

        if (context.Properties.Length > 0)
        {
            sb.AppendLine("var hash = new global::System.HashCode();");
            foreach (var property in context.Properties)
            {
                sb.AppendLine($"hash.Add({property.PropertyName});");
            }
            sb.AppendLine("return hash.ToHashCode();");
        }
        else
        {
            sb.AppendLine("return 0;");
        }

        sb.DecreaseIndent();
        sb.AppendLine("}");
        sb.AppendLine();

        // Equality operators
        sb.AppendLine($"public static bool operator ==({context.DtoClassName}? left, {context.DtoClassName}? right)");
        sb.AppendLine("{");
        sb.IncreaseIndent();
        sb.AppendLine("return global::System.Collections.Generic.EqualityComparer<" + context.DtoClassName + ">.Default.Equals(left, right);");
        sb.DecreaseIndent();
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine($"public static bool operator !=({context.DtoClassName}? left, {context.DtoClassName}? right)");
        sb.AppendLine("{");
        sb.IncreaseIndent();
        sb.AppendLine("return !(left == right);");
        sb.DecreaseIndent();
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void WriteIValidatableObjectImplementation(IndentedStringBuilder sb, DtoGenerationContext context)
    {
        sb.AppendLine("/// <inheritdoc/>");
        sb.AppendLine("public global::System.Collections.Generic.IEnumerable<global::System.ComponentModel.DataAnnotations.ValidationResult> Validate(global::System.ComponentModel.DataAnnotations.ValidationContext validationContext)");
        sb.AppendLine("{");
        sb.IncreaseIndent();

        // Add validation for required properties
        foreach (var property in context.Properties.Where(p => p.IsRequired))
        {
            sb.AppendLine($"if ({property.PropertyName} is null)");
            sb.AppendLine("{");
            sb.IncreaseIndent();
            sb.AppendLine($"yield return new global::System.ComponentModel.DataAnnotations.ValidationResult(\"{property.PropertyName} is required.\", new[] {{ nameof({property.PropertyName}) }});");
            sb.DecreaseIndent();
            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("yield break;");
        sb.DecreaseIndent();
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void WriteToStringOverride(IndentedStringBuilder sb, DtoGenerationContext context)
    {
        sb.AppendLine("/// <inheritdoc/>");
        sb.AppendLine("public override string ToString()");
        sb.AppendLine("{");
        sb.IncreaseIndent();

        var properties = context.Properties.Where(p => !p.Sensitive).ToArray();
        if (properties.Length > 0)
        {
            var propertyStrings = properties
                .Select(p => $"{p.PropertyName} = {{{p.PropertyName}}}");
            // Generate: return $"CustomerDto {{ Id = {Id}, Name = {Name} }}";
            sb.AppendLine($"return $\"{context.DtoClassName} {{{{ {string.Join(", ", propertyStrings)} }}}}\";");
        }
        else
        {
            sb.AppendLine($"return \"{context.DtoClassName}\";");
        }

        sb.DecreaseIndent();
        sb.AppendLine("}");
    }

    private static void WriteJsonAttributes(IndentedStringBuilder sb, PropertyContext property)
    {
        if (property.JsonIgnore)
        {
            sb.AppendLine("[global::System.Text.Json.Serialization.JsonIgnore]");
        }

        if (!string.IsNullOrWhiteSpace(property.JsonPropertyName))
        {
            sb.AppendLine($"[global::System.Text.Json.Serialization.JsonPropertyName(\"{EscapeStringLiteral(property.JsonPropertyName!)}\")]");
        }

        if (!string.IsNullOrWhiteSpace(property.JsonConverterTypeName))
        {
            sb.AppendLine($"[global::System.Text.Json.Serialization.JsonConverter(typeof({property.JsonConverterTypeName}))]");
        }
    }

    private static void WriteDtoValidationAttributes(IndentedStringBuilder sb, PropertyContext property)
    {
        foreach (var validation in property.Validations)
        {
            if (validation.EmailAddress)
                WriteValidationAttribute(sb, "EmailAddress", validation.ErrorMessage);
            if (validation.Phone)
                WriteValidationAttribute(sb, "Phone", validation.ErrorMessage);
            if (validation.Url)
                WriteValidationAttribute(sb, "Url", validation.ErrorMessage);
            if (validation.CreditCard)
                WriteValidationAttribute(sb, "CreditCard", validation.ErrorMessage);
            if (!string.IsNullOrWhiteSpace(validation.CompareProperty))
                WriteValidationAttribute(sb, "Compare", validation.ErrorMessage, $"\"{EscapeStringLiteral(validation.CompareProperty!)}\"");
            if (!string.IsNullOrWhiteSpace(validation.CustomValidationTypeName))
                sb.AppendLine($"[global::System.ComponentModel.DataAnnotations.CustomValidation(typeof({validation.CustomValidationTypeName}), nameof({validation.CustomValidationTypeName}.{validation.CustomValidationMethod}))]");
        }
    }

    private static void WriteValidationAttribute(IndentedStringBuilder sb, string attributeName, string? errorMessage, string? constructorArgument = null)
    {
        var argument = constructorArgument ?? string.Empty;
        var separator = string.IsNullOrEmpty(argument) || string.IsNullOrWhiteSpace(errorMessage) ? string.Empty : ", ";
        var namedArgument = string.IsNullOrWhiteSpace(errorMessage)
            ? string.Empty
            : $"ErrorMessage = \"{EscapeStringLiteral(errorMessage!)}\"";
        sb.AppendLine($"[global::System.ComponentModel.DataAnnotations.{attributeName}({argument}{separator}{namedArgument})]");
    }

    private static string EscapeStringLiteral(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static string EscapeXml(string value)
    {
        return value
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");
    }
}

/// <summary>
/// Helper class for building indented string content.
/// </summary>
internal sealed class IndentedStringBuilder
{
    private readonly StringBuilder _sb = new();
    private int _indentLevel;
    private const string IndentString = "    ";

    public void IncreaseIndent() => _indentLevel++;
    public void DecreaseIndent() => _indentLevel = Math.Max(0, _indentLevel - 1);

    public void AppendLine(string? text = null)
    {
        if (string.IsNullOrEmpty(text))
        {
            _sb.AppendLine();
        }
        else
        {
            _sb.Append(GetIndent());
            _sb.AppendLine(text);
        }
    }

    public void Append(string text)
    {
        _sb.Append(text);
    }

    private string GetIndent()
    {
        return string.Concat(Enumerable.Repeat(IndentString, _indentLevel));
    }

    public override string ToString() => _sb.ToString();
}
