using System;
using System.Linq;
using GenericDto.Analyzers.Extensions;
using GenericDto.Analyzers.Generators.Incremental;
using Microsoft.CodeAnalysis;

namespace GenericDto.Analyzers.Generators;

/// <summary>
/// Builder class responsible for generating mapper extension methods between source types and DTOs.
/// </summary>
internal static class MapperCodeBuilder
{
    public static string GenerateMapper(DtoGenerationContext context)
    {
        var sb = new IndentedStringBuilder();

        // File header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// This code was generated by GenericDto Source Generator.");
        sb.AppendLine("// Do not modify this file manually.");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Usings
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");

        var sourceNamespace = context.SourceType.ContainingNamespace.ToDisplayString();
        if (!string.IsNullOrEmpty(sourceNamespace))
        {
            sb.AppendLine($"using {sourceNamespace};");
        }
        if (context.TargetNamespace != sourceNamespace && context.TargetNamespace != context.MapperNamespace)
        {
            sb.AppendLine($"using {context.TargetNamespace};");
        }
        sb.AppendLine();

        // Namespace
        sb.AppendLine($"namespace {context.MapperNamespace}");
        sb.AppendLine("{");
        sb.IncreaseIndent();

        // Static mapper class
        WriteMapperClass(sb, context);

        sb.DecreaseIndent();
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void WriteMapperClass(IndentedStringBuilder sb, DtoGenerationContext context)
    {
        var sourceTypeName = context.SourceType.Name;
        var sourceTypeFullName = context.SourceType.ToDisplayString();
        var dtoName = context.TargetNamespace == context.MapperNamespace
            ? context.DtoClassName
            : $"{context.TargetNamespace}.{context.DtoClassName}";

        if (context.GenerateDocumentation)
        {
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// Extension methods for mapping between <see cref=\"{sourceTypeFullName}\"/> and <see cref=\"{context.DtoClassName}\"/>.");
            sb.AppendLine("/// </summary>");
        }
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"GenericDto.Analyzers\", \"1.0.0\")]");
        sb.AppendLine("[global::System.Diagnostics.DebuggerNonUserCodeAttribute]");
        sb.AppendLine("[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]");
        sb.AppendLine($"{context.AccessModifier} static class {context.MapperClassName}");
        sb.AppendLine("{");
        sb.IncreaseIndent();

        if (context.GenerateToDto)
        {
            WriteToDto(sb, context, sourceTypeName, sourceTypeFullName, dtoName);
            sb.AppendLine();
        }

        if (context.GenerateToEntity)
        {
            WriteToEntity(sb, context, sourceTypeName, sourceTypeFullName, dtoName);
            sb.AppendLine();
        }

        if (context.GenerateCollectionMappers && context.GenerateToDto)
        {
            WriteToDtoCollection(sb, context, sourceTypeFullName, dtoName);
            sb.AppendLine();
        }

        if (context.GenerateCollectionMappers && context.GenerateToEntity)
        {
            WriteToEntityCollection(sb, context, sourceTypeName, sourceTypeFullName, dtoName);
            sb.AppendLine();
        }

        if (context.GenerateUpdateFrom)
        {
            WriteUpdateEntity(sb, context, sourceTypeName, sourceTypeFullName, dtoName);
        }

        sb.DecreaseIndent();
        sb.AppendLine("}");
    }

    private static void WriteToDto(IndentedStringBuilder sb, DtoGenerationContext context, string sourceTypeName, string sourceTypeFullName, string dtoName)
    {
        var isSourceValueType = context.SourceType.IsValueType;
        
        if (context.GenerateDocumentation)
        {
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// Maps a <see cref=\"{sourceTypeFullName}\"/> instance to a new <see cref=\"{context.DtoClassName}\"/> instance.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine($"/// <param name=\"source\">The source {sourceTypeName} instance.</param>");
            sb.AppendLine($"/// <returns>A new {context.DtoClassName} instance with mapped values.</returns>");
        }
        sb.AppendLine($"public static {dtoName} ToDto(this {sourceTypeFullName} source)");
        sb.AppendLine("{");
        sb.IncreaseIndent();
        
        // Only add null check for reference types
        if (!isSourceValueType)
        {
            sb.AppendLine("if (source is null)");
            sb.AppendLine("{");
            sb.IncreaseIndent();
            sb.AppendLine("throw new global::System.ArgumentNullException(nameof(source));");
            sb.DecreaseIndent();
            sb.AppendLine("}");
            sb.AppendLine();
        }
        
        sb.AppendLine($"return new {dtoName}");
        sb.AppendLine("{");
        sb.IncreaseIndent();

        foreach (var property in context.Properties)
        {
            var sourcePropertyName = string.IsNullOrWhiteSpace(property.MapFrom) ? property.SourceProperty.Name : property.MapFrom!;
            var expression = $"source.{sourcePropertyName}";
            var usesCustomPath = property.Flatten || sourcePropertyName.Contains(".");
            if (HasConverter(property))
            {
                expression = $"{property.ConverterTypeName}.{property.ConverterMethod}({expression})";
            }
            else if (!usesCustomPath && !SymbolEqualityComparer.Default.Equals(property.EffectiveType, property.SourceProperty.Type))
            {
                sb.AppendLine($"// {property.PropertyName}: type overridden - manual mapping required (DTO: '{property.EffectiveType.ToDisplayString()}', Entity: '{property.SourceProperty.Type.ToDisplayString()}').");
                continue;
            }
            sb.AppendLine($"{property.PropertyName} = {expression},");
        }

        sb.DecreaseIndent();
        sb.AppendLine("};");
        sb.DecreaseIndent();
        sb.AppendLine("}");
    }

    private static void WriteToEntity(IndentedStringBuilder sb, DtoGenerationContext context, string sourceTypeName, string sourceTypeFullName, string dtoName)
    {
        // Check if source type has a parameterless constructor
        var hasParameterlessConstructor = context.SourceType.InstanceConstructors
            .Any(c => c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public);

        if (!hasParameterlessConstructor)
        {
            sb.AppendLine("// Note: ToEntity method not generated because source type lacks a public parameterless constructor.");
            return;
        }

        if (context.GenerateDocumentation)
        {
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// Maps a <see cref=\"{context.DtoClassName}\"/> instance to a new <see cref=\"{sourceTypeFullName}\"/> instance.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine($"/// <param name=\"dto\">The source {context.DtoClassName} instance.</param>");
            sb.AppendLine($"/// <returns>A new {sourceTypeName} instance with mapped values.</returns>");
        }
        sb.AppendLine($"public static {sourceTypeFullName} ToEntity(this {dtoName} dto)");
        sb.AppendLine("{");
        sb.IncreaseIndent();
        sb.AppendLine("if (dto is null)");
        sb.AppendLine("{");
        sb.IncreaseIndent();
        sb.AppendLine("throw new global::System.ArgumentNullException(nameof(dto));");
        sb.DecreaseIndent();
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"return new {sourceTypeFullName}");
        sb.AppendLine("{");
        sb.IncreaseIndent();

        // Only map properties that have a setter on the source type
        var explicitReverseTargets = new global::System.Collections.Generic.HashSet<string>(
            context.Properties
                .Where(p => !string.IsNullOrWhiteSpace(p.MapTo))
                .Select(p => p.MapTo!),
            StringComparer.Ordinal);
        var initializedTargets = new global::System.Collections.Generic.HashSet<string>(StringComparer.Ordinal);

        foreach (var property in context.Properties)
        {
            if (property.IgnoreReverseMap)
                continue;
            if (property.Flatten && string.IsNullOrWhiteSpace(property.MapTo))
                continue;

            var sourceProperty = property.SourceProperty;
            if (sourceProperty.SetMethod != null && sourceProperty.SetMethod.DeclaredAccessibility == Accessibility.Public)
            {
                var targetPropertyName = string.IsNullOrWhiteSpace(property.MapTo) ? sourceProperty.Name : property.MapTo!;
                if (explicitReverseTargets.Contains(targetPropertyName) && string.IsNullOrWhiteSpace(property.MapTo))
                    continue;
                if (!initializedTargets.Add(targetPropertyName))
                    continue;

                var expression = $"dto.{property.PropertyName}";
                if (HasConverter(property))
                {
                    expression = $"{property.ConverterTypeName}.{property.ConverterMethod}({expression})";
                }
                else if (!SymbolEqualityComparer.Default.Equals(property.EffectiveType, sourceProperty.Type))
                {
                    sb.AppendLine($"// {sourceProperty.Name}: type overridden - manual mapping required (DTO: '{property.EffectiveType.ToDisplayString()}', Entity: '{sourceProperty.Type.ToDisplayString()}').");
                    continue;
                }
                sb.AppendLine($"{targetPropertyName} = {expression},");
            }
        }

        sb.DecreaseIndent();
        sb.AppendLine("};");
        sb.DecreaseIndent();
        sb.AppendLine("}");
    }

    private static void WriteToDtoCollection(IndentedStringBuilder sb, DtoGenerationContext context, string sourceTypeFullName, string dtoName)
    {
        if (context.GenerateDocumentation)
        {
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// Maps a collection of <see cref=\"{sourceTypeFullName}\"/> instances to a list of <see cref=\"{context.DtoClassName}\"/> instances.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("/// <param name=\"source\">The source collection.</param>");
            sb.AppendLine($"/// <returns>A list of {context.DtoClassName} instances with mapped values.</returns>");
        }
        sb.AppendLine($"public static global::System.Collections.Generic.List<{dtoName}> ToDtoList(this global::System.Collections.Generic.IEnumerable<{sourceTypeFullName}> source)");
        sb.AppendLine("{");
        sb.IncreaseIndent();
        sb.AppendLine("if (source is null)");
        sb.AppendLine("{");
        sb.IncreaseIndent();
        sb.AppendLine("throw new global::System.ArgumentNullException(nameof(source));");
        sb.DecreaseIndent();
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"var result = source is global::System.Collections.Generic.ICollection<{sourceTypeFullName}> collection");
        sb.AppendLine($"    ? new global::System.Collections.Generic.List<{dtoName}>(collection.Count)");
        sb.AppendLine($"    : new global::System.Collections.Generic.List<{dtoName}>();");
        sb.AppendLine("foreach (var item in source)");
        sb.AppendLine("{");
        sb.IncreaseIndent();
        sb.AppendLine("result.Add(ToDto(item));");
        sb.DecreaseIndent();
        sb.AppendLine("}");
        sb.AppendLine("return result;");
        sb.DecreaseIndent();
        sb.AppendLine("}");
    }

    private static void WriteToEntityCollection(IndentedStringBuilder sb, DtoGenerationContext context, string sourceTypeName, string sourceTypeFullName, string dtoName)
    {
        // Check if source type has a parameterless constructor
        var hasParameterlessConstructor = context.SourceType.InstanceConstructors
            .Any(c => c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public);

        if (!hasParameterlessConstructor)
        {
            sb.AppendLine("// Note: ToEntityList method not generated because source type lacks a public parameterless constructor.");
            return;
        }

        if (context.GenerateDocumentation)
        {
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// Maps a collection of <see cref=\"{context.DtoClassName}\"/> instances to a list of <see cref=\"{sourceTypeFullName}\"/> instances.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("/// <param name=\"dtos\">The source DTO collection.</param>");
            sb.AppendLine($"/// <returns>A list of {sourceTypeName} instances with mapped values.</returns>");
        }
        sb.AppendLine($"public static global::System.Collections.Generic.List<{sourceTypeFullName}> ToEntityList(this global::System.Collections.Generic.IEnumerable<{dtoName}> dtos)");
        sb.AppendLine("{");
        sb.IncreaseIndent();
        sb.AppendLine("if (dtos is null)");
        sb.AppendLine("{");
        sb.IncreaseIndent();
        sb.AppendLine("throw new global::System.ArgumentNullException(nameof(dtos));");
        sb.DecreaseIndent();
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"var result = dtos is global::System.Collections.Generic.ICollection<{dtoName}> collection");
        sb.AppendLine($"    ? new global::System.Collections.Generic.List<{sourceTypeFullName}>(collection.Count)");
        sb.AppendLine($"    : new global::System.Collections.Generic.List<{sourceTypeFullName}>();");
        sb.AppendLine("foreach (var dto in dtos)");
        sb.AppendLine("{");
        sb.IncreaseIndent();
        sb.AppendLine("result.Add(ToEntity(dto));");
        sb.DecreaseIndent();
        sb.AppendLine("}");
        sb.AppendLine("return result;");
        sb.DecreaseIndent();
        sb.AppendLine("}");
    }

    private static void WriteUpdateEntity(IndentedStringBuilder sb, DtoGenerationContext context, string sourceTypeName, string sourceTypeFullName, string dtoName)
    {
        var isSourceValueType = context.SourceType.IsValueType;
        
        if (context.GenerateDocumentation)
        {
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// Updates an existing <see cref=\"{sourceTypeFullName}\"/> instance with values from a <see cref=\"{context.DtoClassName}\"/>.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("/// <param name=\"entity\">The entity to update.</param>");
            sb.AppendLine("/// <param name=\"dto\">The DTO containing the new values.</param>");
            sb.AppendLine("/// <returns>The updated entity instance.</returns>");
        }
        sb.AppendLine($"public static {sourceTypeFullName} UpdateFrom(this {sourceTypeFullName} entity, {dtoName} dto)");
        sb.AppendLine("{");
        sb.IncreaseIndent();
        
        // Only add null check for reference types
        if (!isSourceValueType)
        {
            sb.AppendLine("if (entity is null)");
            sb.AppendLine("{");
            sb.IncreaseIndent();
            sb.AppendLine("throw new global::System.ArgumentNullException(nameof(entity));");
            sb.DecreaseIndent();
            sb.AppendLine("}");
            sb.AppendLine();
        }
        
        sb.AppendLine("if (dto is null)");
        sb.AppendLine("{");
        sb.IncreaseIndent();
        sb.AppendLine("throw new global::System.ArgumentNullException(nameof(dto));");
        sb.DecreaseIndent();
        sb.AppendLine("}");
        sb.AppendLine();

        // Only update properties that have a setter on the source type
        var explicitReverseTargets = new global::System.Collections.Generic.HashSet<string>(
            context.Properties
                .Where(p => !string.IsNullOrWhiteSpace(p.MapTo))
                .Select(p => p.MapTo!),
            StringComparer.Ordinal);
        var updatedTargets = new global::System.Collections.Generic.HashSet<string>(StringComparer.Ordinal);

        foreach (var property in context.Properties)
        {
            if (property.IgnoreReverseMap)
                continue;
            if (property.Flatten && string.IsNullOrWhiteSpace(property.MapTo))
                continue;

            var sourceProperty = property.SourceProperty;
            if (sourceProperty.SetMethod != null && sourceProperty.SetMethod.DeclaredAccessibility == Accessibility.Public)
            {
                var targetPropertyName = string.IsNullOrWhiteSpace(property.MapTo) ? sourceProperty.Name : property.MapTo!;
                if (explicitReverseTargets.Contains(targetPropertyName) && string.IsNullOrWhiteSpace(property.MapTo))
                    continue;
                if (!updatedTargets.Add(targetPropertyName))
                    continue;

                var expression = $"dto.{property.PropertyName}";
                if (HasConverter(property))
                {
                    expression = $"{property.ConverterTypeName}.{property.ConverterMethod}({expression})";
                }
                else if (!SymbolEqualityComparer.Default.Equals(property.EffectiveType, sourceProperty.Type))
                {
                    sb.AppendLine($"// {sourceProperty.Name}: type overridden - manual mapping required (DTO: '{property.EffectiveType.ToDisplayString()}', Entity: '{sourceProperty.Type.ToDisplayString()}').");
                    continue;
                }
                sb.AppendLine($"entity.{targetPropertyName} = {expression};");
            }
        }

        sb.AppendLine();
        sb.AppendLine("return entity;");
        sb.DecreaseIndent();
        sb.AppendLine("}");
    }

    private static bool HasConverter(PropertyContext property)
    {
        return !string.IsNullOrWhiteSpace(property.ConverterTypeName) &&
               !string.IsNullOrWhiteSpace(property.ConverterMethod);
    }
}
